[project]
name = "letterboxint"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi[standard]>=0.122.0",
    "pyjwt>=2.10.1",
    "sqlmodel>=0.0.27",
]
